### ISSUE TITLE
Revise Editor

### ISSUE THREAD

**Issue by schubmat** [schubmat/Custom-MADE#13]
As of now, the editor is implemented with the help of a standalone instance of the Monaco Editor using an old very undesirable iframe. This needs to be done properly.

Either the project needs to be revised, so that Custom-MADE will use the
* ReactJS-Monaco,
or we are going to replace Monaco by an entirely new approach like Sprotty, respectively recent research results developed by @rrcomtech.

**Comment by schubmat** [comment]
@rrcomtech Did your recent search yield any new insights on how to display and transform circular graphs into ECore. Could we, thus, use your recent research results?

**Comment by judgeNotFound** [comment]
To put it short: yes, we can use cyclic graphs. This is achieved by using cross-references and adding support to the language server to handle those references.

The example language server with cross-reference handling, which could be generated by an M2-generator, is given under the following umbrella repository (links to a frontend project and the language server):

[https://github.com/rrcomtech/Visualization_of_DSL_Families](https://github.com/rrcomtech/Visualization_of_DSL_Families)

**Comment by schubmat** [comment]
@rrcomtech In which way does Theia recognise the approach of renaming `mdr-dsl` into any other arbitrary folder as a plugin to start? 

Ref: We talked about introducing an abstraction that allows for using multiple languages with the Theia approach. Thus, the folder will be named something unknown atm.

**Comment by judgeNotFound** [comment]
The folder `mdr-dsl`, which is a Theia extension, is referenced by the actual browser application. The application is located in the `browser-app` folder and identified by the `package.json`. There you will find an entry containing the name(s) of the Theia extension(s), which includes `mdr-dsl`. So to rename the folder of a Theia extension, simply change the folder name and the entry in the `browser-app/package.json`.

New Theia extensions are added in a similar way. 

To add more languages to Theia, one should copy the folder template (formerly named `mdr-dsl`) and apply the necessary domain-specific changes (path to language server, file extension, ...). Finally add the new folder name to the list of Theia extensions in `browser-app/package.json`.

Visualization support is included, if the `mdr-dsl` template is used. For that it heavily relies on `mdr-sprotty`.

**Comment by schubmat** [comment]
@rrcomtech please see pull request #34

**Comment by schubmat** [comment]
This issue will be of the next release (supposedly 0.1.0).
