### ISSUE TITLE
Manage LSP Server Termination

### ISSUE THREAD

**Issue by schubmat** [schubmat/Custom-MADE#14]
The termination of all connected LSP Server instances is yet to be optimised. It should be augmented by the following behaviours.

* [x] Once a user terminates his/her session, all connected LSPs will be terminated.
* [x] Once the user authentication times out, all connected LSPs will be terminated.

In other words, as soon as a LSP Server instance is not used anymore it should be terminated to save resources.

**Comment by judgeNotFound** [comment]
Is this still open? Both tasks seem to be done, since they are managed by Theia.

**Comment by schubmat** [comment]
@rrcomtech Actually, it has not yet been done entirely. The backend still contains code to start / terminate running LSP instances. It should be freed from it before closing this issue I'd say. Any objections?

**Comment by judgeNotFound** [comment]
@schubmat No, I have no objections. This is a very good point.

**Comment by schubmat** [comment]
@rrcomtech done
