### ISSUE TITLE
Fix Blocker Bugs

### ISSUE THREAD

**Issue by schubmat** [schubmat/Custom-MADE#5]
@rrcomtech @ronnyporsch @pcprinz 

In order to improve comprehensibility, maintainability and overall quality 

* **blocker bugs** detected by SonarQube 

need to be removed in the *backend* subproject.

**Comment by schubmat** [comment]
@pcprinz Please check SonarQube again, there is a bug assigned to you, not fixed yet.

@pcprinz @ronnyporsch @rrcomtech 
Please check the recent SonarQube scan. A new bug appeared

**Comment by achillease** [comment]
I fixed the remaining bug in the fix/blocker_bugs branch
